logging:
  file:
    path: /app/logs

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/ticket_queue?currentSchema=reservation_service,common
    username: reservation_svc_user
    password: ${db_password}
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: kafka:29092
  cloud:
    openfeign:
      client:
        config:
          event-service:
            url: http://event-service:8082
