spring:
  config:
    activate:
      on-profile: local
    import:
      - "optional:aws-secretsmanager:common/secure-config"
  data:
    redis:
      host: 192.168.50.111
      port: 6379
      password: ${valkey_password}

encryption:
  secret-key: ${enc_secret_key}
  hash-salt: ${enc_hash_salt}

external:
  portone:
    api-url: https://api.portone.io
    api-secret: ${portone_api_secret}
    store-id: ${portone_store_id}
    channel-key: ${portone_channel_key}
