spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://192.168.50.111:5432/ticket_queue?currentSchema=user_service,common
    username: user_svc_user
    password: ${db_password}
    driver-class-name: org.postgresql.Driver

jwt:
  secret: ${jwt_secret}
  accessTokenExpiry: 3600000
  refreshTokenExpiry: 604800000

security:
  trusted-proxy-ips: "127.0.0.1,::1"

external:
  portone:
    enabled: true