export const ERROR_CODES = {
  // Queue
  NOT_IN_QUEUE: 'NOT_IN_QUEUE',
  ALREADY_IN_QUEUE: 'ALREADY_IN_QUEUE',
  ALREADY_APPROVED: 'ALREADY_APPROVED',
  QUEUE_FULL: 'QUEUE_FULL',
  QUEUE_TOKEN_EXPIRED: 'QUEUE_TOKEN_EXPIRED',
  QUEUE_TOKEN_INVALID: 'QUEUE_TOKEN_INVALID',
  // Reservation
  SEAT_ALREADY_HELD: 'SEAT_ALREADY_HELD',
  MAX_SEATS_EXCEEDED: 'MAX_SEATS_EXCEEDED',
  HOLD_EXPIRED: 'HOLD_EXPIRED',
  RESERVATION_NOT_FOUND: 'RESERVATION_NOT_FOUND',
  // Payment
  DUPLICATE_PAYMENT: 'DUPLICATE_PAYMENT',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  // User
  ALREADY_EXISTS_EMAIL: 'ALREADY_EXISTS_EMAIL',
  DUPLICATE_IDENTITY: 'DUPLICATE_IDENTITY',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]
