server:
  port: 8083

spring:
  application:
    name: queue-service
  config:
    import:
      - "optional:classpath:/application-common-${spring.profiles.active}.yml"
      - "optional:aws-secretsmanager:queue-svc/secure-config"

queue:
  batch:
    size: 10
    interval: 1000
  token:
    ttl: 600
  max-capacity: 50000
  active-user:
    ttl: 600
  rate-limit:
    max-requests: 15
    window-seconds: 60

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always
