global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9080']
    relabel_configs:
      - target_label: application
        replacement: api-gateway

  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9081']
    relabel_configs:
      - target_label: application
        replacement: user-service

  - job_name: 'event-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9082']
    relabel_configs:
      - target_label: application
        replacement: event-service

  - job_name: 'queue-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9083']
    relabel_configs:
      - target_label: application
        replacement: queue-service

  - job_name: 'reservation-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9084']
    relabel_configs:
      - target_label: application
        replacement: reservation-service

  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:9085']
    relabel_configs:
      - target_label: application
        replacement: payment-service
